apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVervsion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":"2021-01-12T12:13:03Z","labels":{"key":"FreezeTuesday","run":"nginx"},"name":"nginx","namespace":"user-14","resourceVersion":"1964154","selfLink":"/api/v1/namespaces/user-14/pods/nginx","uid":"f5df54c3-136c-45dc-a84e-2919e1fe7cf8"},"spec":{"containers":[{"image":"nginx:latest","imagePullPolicy":"Always","name":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"default-token-vvggl","readOnly":true}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"gke-esun-lecture-1-pool-4-4303c2db-nl3f","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"default-token-vvggl","secret":{"defaultMode":420,"secretName":"default-token-vvggl"}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2021-01-12T12:13:03Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-12T12:13:10Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-12T12:13:10Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-12T12:13:03Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"docker://9121dbcaf1398225eb19b65f469f6ec939ab6a74c9bad6b34c79412c2f5383b4","image":"nginx:latest","imageID":"docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa","lastState":{},"name":"nginx","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2021-01-12T12:13:09Z"}}}],"hostIP":"10.170.0.49","phase":"Running","podIP":"10.60.3.8","podIPs":[{"ip":"10.60.3.8"}],"qosClass":"BestEffort","startTime":"2021-01-12T12:13:03Z"}}
  creationTimestamp: "2021-01-12T12:38:00Z"
  labels:
    key: FreezeTuesday
    run: nginx
  name: nginx
  namespace: user-14
  resourceVersion: "1970367"
  selfLink: /api/v1/namespaces/user-14/pods/nginx
  uid: c29b3dd2-c36c-4db0-8f77-b1734001b00c
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: admin
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: htmldir
      readOnly: true
  - image: busybox:latest
    imagePullPolicy: Always
    name: busybox
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: admin
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do echo $DUMMY_DATABASE_PASSWORD >> /html/index.html && sleep 5; done;"]
    volumeMounts:
    - mountPath: /html
      name: htmldir
    startupProbe:
      httpGet:
        path: /
        port: 80
        #httpHeaders:
        #  - name: Custom-Header
        #    value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-nl3f
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: htmldir
    emptyDir: {}
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-12T12:38:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-12T12:38:02Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-12T12:38:02Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-12T12:38:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0f3524962d0ae47f6638bbd6bd4058145cb3e1f68685ef5ee069abd955d97497
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-12T12:38:02Z"
  hostIP: 10.170.0.49
  phase: Running
  podIP: 10.60.3.9
  podIPs:
  - ip: 10.60.3.9
  qosClass: BestEffort
  startTime: "2021-01-12T12:38:00Z"
